
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: myapp-argo-application
  namespace: argocd
spec: 
  destination: 
    namespace: my-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: k8s
    repoURL: "git@github.com:Seweryn1777/argocd.git"
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true