apiVersion: v1
kind: ConfigMap
metadata:
  name: order-envars
  namespace: default
data:
  API_HOST: '0.0.0.0'
  API_PORT: '3000'
  USE_LOGS: 'true'
  REDIS_HOST: 'redis.datalayer.svc.cluster.local'
  REDIS_PREFIX: 'order-api'
  TYPEORM_CONNECTION: 'mysql'
  TYPEORM_DEBUG: 'false'
  TYPEORM_HOST: 'speakeasy.csddm1yfwy1k.eu-central-1.rds.amazonaws.com'
  TYPEORM_LOGGING: 'true'
  TYPEORM_PORT: '3306'
  TYPEORM_SYNCHRONIZE: 'false'
  TYPEORM_MIGRATIONS: 'dist/migrations/*.js'
  TYPEORM_DATABASE: 'order'
  STRIPE_RETURN_URL: 'speak-easy.com/api/order/webhook'
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: default
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - port: 3000
      name: http-3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: default
  labels:
    app: order
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: order
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order:1
          envFrom:
            - configMapRef:
                name: order-envars
            - configMapRef:
                name: common-envars
          env:
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sealed-secrets
                  key: TYPEORM_USERNAME
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sealed-secrets
                  key: TYPEORM_PASSWORD
            - name: JWT_TOKEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: sealed-secrets
                  key: JWT_TOKEN_PRIVATE_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sealed-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: sealed-secrets
                  key: STRIPE_PUBLISHABLE_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sealed-secrets
                  key: STRIPE_SECRET_KEY
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              name: order
          livenessProbe:
            httpGet:
              path: /health-check
              port: 3000
            initialDelaySeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health-check
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
      restartPolicy: Always